#!/usr/bin/env bun
// ---------------------------------------------------------------------------
// Regenerates src/prompt-hashes.ts.
//
// Walks every `v*` git tag plus the current working tree for each
// prompts/*.md file, hashes its normalized content, and accumulates a
// PROMPT_HASH_HISTORY so `reconcile-prompts` (src/prompt-sync.ts) can
// recognize "this disk file matches some previously-shipped default" even
// across several releases of edits.
//
// Run this (`bun run build:prompt-hashes`) any time prompts/*.md changes,
// before tagging a release — see AGENTS.md.
// ---------------------------------------------------------------------------

import { execSync } from "child_process"
import { readdirSync, readFileSync, writeFileSync } from "fs"
import { createHash } from "crypto"
import { join } from "path"

const ROOT = join(import.meta.dir, "..")
const PROMPTS_DIR = join(ROOT, "prompts")
const OUT_FILE = join(ROOT, "src", "prompt-hashes.ts")

function normalizePrompt(s: string): string {
  return s.replace(/\r\n/g, "\n").trim()
}

function hashPrompt(s: string): string {
  return createHash("sha256").update(normalizePrompt(s), "utf-8").digest("hex")
}

function sh(cmd: string): string {
  return execSync(cmd, { cwd: ROOT, encoding: "utf-8" })
}

const filenames = readdirSync(PROMPTS_DIR)
  .filter((f) => f.endsWith(".md"))
  .sort()

const tags = sh("git tag --list 'v*'")
  .split("\n")
  .map((t) => t.trim())
  .filter(Boolean)

const history: Record<string, string[]> = {}
for (const filename of filenames) history[filename] = []

function addHash(filename: string, hash: string): void {
  if (!history[filename].includes(hash)) history[filename].push(hash)
}

for (const tag of tags) {
  for (const filename of filenames) {
    try {
      const content = sh(`git show ${tag}:prompts/${filename}`)
      addHash(filename, hashPrompt(content))
    } catch {
      // File didn't exist at this tag yet — skip.
    }
  }
}

// Current working tree content is appended last — it's the newest default,
// including any uncommitted edits about to ship.
for (const filename of filenames) {
  const content = readFileSync(join(PROMPTS_DIR, filename), "utf-8")
  addHash(filename, hashPrompt(content))
}

const body = `// ---------------------------------------------------------------------------
// GENERATED by scripts/gen-prompt-hashes.ts — do not edit manually.
// Run \`bun run build:prompt-hashes\` after changing prompts/*.md, before
// tagging a release. See AGENTS.md for the prompt-reconciliation flow.
// ---------------------------------------------------------------------------

import { createHash } from "crypto"

/** Strip CRLF and surrounding whitespace so disk/bundled comparisons agree. */
export function normalizePrompt(s: string): string {
  return s.replace(/\\r\\n/g, "\\n").trim()
}

/** sha256 hex of the normalized content. */
export function hashPrompt(s: string): string {
  return createHash("sha256").update(normalizePrompt(s), "utf-8").digest("hex")
}

/**
 * Every distinct default hash ever shipped for each bundled prompt filename,
 * oldest first. A disk file whose hash appears here (but isn't the current
 * default) is classified as "unedited" and safe to overwrite.
 */
export const PROMPT_HASH_HISTORY: Record<string, string[]> = ${JSON.stringify(history, null, 2)}
`

writeFileSync(OUT_FILE, body, "utf-8")
console.log(`Wrote ${OUT_FILE}`)
for (const filename of filenames) {
  console.log(`  ${filename}: ${history[filename].length} historical hash(es)`)
}
