// ---------------------------------------------------------------------------
// Bundled seed assets — embedded at compile time via import attributes.
//
// Bun's bundler (both `bun run` and `bun build --compile`) inlines files
// imported with `with { type: "text" }` directly into the JS bundle, so these
// strings are available even inside a compiled binary where `import.meta.url`
// filesystem paths no longer resolve to the source tree.
//
// IMPORTANT: If you add a prompt file to prompts/, you must also add a static
// import here and an entry in BUNDLED_PROMPTS — the manifest is explicit.
//
// IMPORTANT: The pre-built worker JS (src/worker/bun-worker-shim.js) is
// generated by `bun run build:worker`. Re-run it whenever @opentui/core updates
// so the embedded tree-sitter runtime stays in sync.
// ---------------------------------------------------------------------------

import configExample from "../config.example.yaml" with { type: "text" }
import globalMd from "../prompts/_global.md" with { type: "text" }
import defaultMd from "../prompts/0-default.md" with { type: "text" }
import hackerMd from "../prompts/1-hacker.md" with { type: "text" }
import developerMd from "../prompts/2-developer.md" with { type: "text" }
import writerMd from "../prompts/3-writer.md" with { type: "text" }
import workerJs from "./worker/bun-worker-shim.js" with { type: "text" }
import updateSh from "../scripts/update.sh" with { type: "text" }
import uninstallSh from "../scripts/uninstall.sh" with { type: "text" }

/** The config.example.yaml content, bundled at compile time. */
export const BUNDLED_CONFIG: string = configExample

/**
 * All bundled persona + global prompt files.
 * Keys are the filenames to write into the user's prompts/ directory on first run.
 */
export const BUNDLED_PROMPTS: Record<string, string> = {
  "_global.md": globalMd,
  "0-default.md": defaultMd,
  "1-hacker.md": hackerMd,
  "2-developer.md": developerMd,
  "3-writer.md": writerMd,
}

/**
 * Pre-bundled tree-sitter worker JS (bun-worker-shim.ts compiled with bun build --target=bun).
 * Written to the data dir on first run alongside its wasm dependency (tree-sitter.wasm).
 * Generated by `bun run build:worker` — do not edit manually.
 */
export const BUNDLED_WORKER_JS: string = workerJs

/**
 * Shell scripts embedded in the binary so `openchat update` / `openchat uninstall`
 * work without any external files. Written to a temp path and exec'd via bash.
 * Source of truth lives in scripts/ — do not duplicate logic here.
 */
export const UPDATE_SH: string = updateSh
export const UNINSTALL_SH: string = uninstallSh
