// ---------------------------------------------------------------------------
// GENERATED by scripts/gen-prompt-hashes.ts — do not edit manually.
// Run `bun run build:prompt-hashes` after changing prompts/*.md, before
// tagging a release. See AGENTS.md for the prompt-reconciliation flow.
// ---------------------------------------------------------------------------

import { createHash } from "crypto"

/** Strip CRLF and surrounding whitespace so disk/bundled comparisons agree. */
export function normalizePrompt(s: string): string {
  return s.replace(/\r\n/g, "\n").trim()
}

/** sha256 hex of the normalized content. */
export function hashPrompt(s: string): string {
  return createHash("sha256").update(normalizePrompt(s), "utf-8").digest("hex")
}

/**
 * Every distinct default hash ever shipped for each bundled prompt filename,
 * oldest first. A disk file whose hash appears here (but isn't the current
 * default) is classified as "unedited" and safe to overwrite.
 */
export const PROMPT_HASH_HISTORY: Record<string, string[]> = {
  "0-default.md": [
    "3283383fcd6b2705b13a9b6ca23964c79ff0b04c338db96574618b1f6d1b234f",
    "28a7bc9f0d150cae8934a273462414b1fc39d0d4d72554fd8d4c72b9cf626cb6"
  ],
  "1-hacker.md": [
    "72d21b62a518e3f1f2749ab23c204a6ef7dfff416bd3a5072c19cd2a56d4e5ef",
    "3094280c8c933153054f88d2874f164e80a6f153d1ff0b5ce3cf30f822610139"
  ],
  "2-developer.md": [
    "9733b0d235ebd93a5c3f40629a33f212768446e5c700f2b27800cc3802535ea5",
    "7c8c9506e0723e4a8b0dac9bfff3cb53a7653233225ba4ec1a4781ab3e827354"
  ],
  "3-writer.md": [
    "255122d7668fd1fe7fd064c6c533118e784653e3a19a20e9e2a8c0f7e3a2a50b",
    "fe8eb77b27db2b3fad40a5201ab3c21abe1630e997e54c985b86af95ae46e856"
  ],
  "_global.md": [
    "c9a56e039ae5f33d573a68c84bd19af357e55049d27b228d78458cb1db7ea05f",
    "c7ccab3acc35ab675ab8eff96bc8b5a989ca8ecb40b8268e759743ffe0df2754"
  ]
}
